spring:
  data:
    redis:
      password: naamkadmin # docker에 설정된 패스워드 가져오기
      sentinel:
        master: mymaster
        nodes: # sentinel.conf에 설정된 host값 가져오기 필요.
          - 127.0.0.1:26379
          - 127.0.0.1:26380
          - 127.0.0.1:26381
      lettuce:
        shutdown-timeout: 200ms