version: "3.8"
services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    restart: always # 컨테이너가 예기치 않게 종료되었을 때 자동으로 재시작됨.
    ports:
      - "6379:6379"
    volumes:
      - ./redis-master/data:/data
      - ./redis-master/redis-master.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    networks:
      - redis-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 5
      timeout: 3s

  redis-slave1:
    image: redis:latest
    container_name: redis-slave1
    volumes:
      - ./redis-slave1/data:/data
      - ./redis-slave1/redis-slave.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    networks:
      - redis-network
    depends_on:
      - redis-master

  redis-slave2:
    image: redis:latest
    container_name: redis-slave2
    volumes:
      - ./redis-slave2/data:/data
      - ./redis-slave2/redis-slave.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    networks:
      - redis-network
    depends_on:
      - redis-master



  sentinel-1:
    image: redis:latest
    hostname: sentinel-1
    container_name: sentinel-1
    restart: always
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel-1:/etc/redis
    entrypoint: ["/bin/sh", "-c", "cp /etc/redis/sentinel.conf.bak /etc/redis/sentinel.conf && redis-server /etc/redis/sentinel.conf --sentinel"]
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
    networks:
      - redis-network

  sentinel-2:
    image: redis:latest
    hostname: sentinel-2
    container_name: sentinel-2
    restart: always
    ports:
      - "26380:26379"
    volumes:
      - ./sentinel-2:/etc/redis
    entrypoint: ["/bin/sh", "-c", "cp /etc/redis/sentinel.conf.bak /etc/redis/sentinel.conf && redis-server /etc/redis/sentinel.conf --sentinel"]
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
    networks:
      - redis-network

  sentinel-3:
    image: redis:latest
    hostname: sentinel-3
    container_name: sentinel-3
    restart: always
    ports:
      - "26381:26379"
    volumes:
      - ./sentinel-3:/etc/redis
    entrypoint: ["/bin/sh", "-c", "cp /etc/redis/sentinel.conf.bak /etc/redis/sentinel.conf && redis-server /etc/redis/sentinel.conf --sentinel"]
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
    networks:
      - redis-network



networks:
  redis-network:
    driver: bridge

